ALTER TABLE connector_credential_pairs
    ADD COLUMN full_recollect_requested BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE embedding_providers (
    provider_type VARCHAR(64) PRIMARY KEY,
    api_url TEXT NOT NULL,
    api_key_encrypted TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_embedding_provider_type CHECK (provider_type = 'OPENAI_COMPATIBLE')
);

CREATE TABLE search_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(512) NOT NULL,
    model_dim INTEGER NOT NULL,
    normalize BOOLEAN NOT NULL,
    query_prefix TEXT,
    passage_prefix TEXT,
    provider_type VARCHAR(64) REFERENCES embedding_providers(provider_type) ON DELETE SET NULL,
    index_name VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(16) NOT NULL,
    singleton_marker SMALLINT,
    reindex_started_at TIMESTAMP WITH TIME ZONE,
    cancel_requested_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_search_settings_model_dim CHECK (model_dim > 0),
    CONSTRAINT ck_search_settings_status CHECK (status IN ('PRESENT', 'FUTURE', 'PAST')),
    CONSTRAINT ck_search_settings_singleton_marker CHECK (
        (status IN ('PRESENT', 'FUTURE') AND singleton_marker = 1)
        OR (status = 'PAST' AND singleton_marker IS NULL)
    ),
    CONSTRAINT uq_search_settings_live_status UNIQUE (status, singleton_marker)
);

CREATE TABLE reindex_port_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_settings_id BIGINT NOT NULL REFERENCES search_settings(id) ON DELETE CASCADE,
    cc_pair_id BIGINT NOT NULL REFERENCES connector_credential_pairs(id) ON DELETE CASCADE,
    status VARCHAR(16) NOT NULL DEFAULT 'NOT_STARTED',
    last_processed_document_id VARCHAR(2048),
    up_to_document_id VARCHAR(2048),
    documents_ported BIGINT NOT NULL DEFAULT 0,
    claim_token UUID,
    claimed_by VARCHAR(256),
    lease_expires_at TIMESTAMP WITH TIME ZONE,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reindex_port_status CHECK (
        status IN ('NOT_STARTED', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'CANCELED')
    ),
    CONSTRAINT uq_reindex_port_pair UNIQUE (search_settings_id, cc_pair_id)
);

CREATE INDEX idx_reindex_port_claimable
    ON reindex_port_attempts(status, lease_expires_at, id);
